-- BindPad + MegaMacro consolidated UI
-- Generated by Stage 5 Safe from the user's known-working UI modules.
-- SavedVariables and MegaMacro data loading are intentionally untouched.

-- ============================================================
-- BEGIN: Style.lua
-- ============================================================
do
local _, addon = ...

local BPMM = _G.BPMM
if not BPMM then return end

local MASK = "Interface\\AddOns\\BetterBind\\UI\\media\\roundedmask"

local C = {
    bg      = {0.035, 0.035, 0.040, 0.98},
    panel   = {0.060, 0.060, 0.070, 0.96},
    panel2  = {0.085, 0.085, 0.095, 0.96},
    hover   = {0.16,  0.16,  0.18,  1},
    accent  = {0.10,  0.55,  0.85,  1},
    text    = {0.90,  0.90,  0.92,  1},
    muted   = {0.55,  0.55,  0.58,  1},
    black   = {0,0,0,1},
}

local styled = setmetatable({}, {__mode="k"})
local rounded = setmetatable({}, {__mode="k"})
local dragAreas = {}
local updateFrame

local function SetBackdrop(frame, bg, border)
    if not frame or not frame.SetBackdrop then return end
    frame:SetBackdrop({
        bgFile = "Interface\\Buttons\\WHITE8x8",
        edgeFile = "Interface\\Buttons\\WHITE8x8",
        edgeSize = 1,
        insets = {left=1,right=1,top=1,bottom=1},
    })
    local b = bg or C.panel
    frame:SetBackdropColor(b[1],b[2],b[3],b[4])
    local e = border or C.black
    frame:SetBackdropBorderColor(e[1],e[2],e[3],e[4])
end

local function CreateShell(frame, bg)
    if not frame or frame.__BPMMShell then return end
    local shell = CreateFrame("Frame", nil, frame, "BackdropTemplate")
    shell:SetPoint("TOPLEFT", frame, "TOPLEFT", 0, 0)
    shell:SetPoint("BOTTOMRIGHT", frame, "BOTTOMRIGHT", 0, 0)
    shell:SetFrameLevel(math.max(0,frame:GetFrameLevel()-1))
    SetBackdrop(shell,bg or C.bg,C.black)
    frame.__BPMMShell = shell
end

local function RoundTexture(tex)
    if not tex or rounded[tex] then return end
    if not tex.GetTexture or not tex:GetTexture() then return end
    rounded[tex] = true
    if tex.SetTexCoord then
        tex:SetTexCoord(0.07,0.93,0.07,0.93)
    end
    if tex.CreateMaskTexture and tex.AddMaskTexture then
        local mask = tex:CreateMaskTexture()
        mask:SetTexture(MASK,"CLAMPTOBLACKADDITIVE","CLAMPTOBLACKADDITIVE")
        mask:SetAllPoints(tex)
        tex:AddMaskTexture(mask)
        tex.__BPMMMask = mask
    end
end

local function HideTexture(tex)
    if tex and tex.SetAlpha then tex:SetAlpha(0) end
end

local function FlatButton(button, danger)
    if not button or styled[button] then return end
    styled[button]=true

    if button.GetNormalTexture then HideTexture(button:GetNormalTexture()) end
    if button.GetPushedTexture then HideTexture(button:GetPushedTexture()) end
    if button.GetDisabledTexture then HideTexture(button:GetDisabledTexture()) end
    if button.GetHighlightTexture then HideTexture(button:GetHighlightTexture()) end

    local bg = CreateFrame("Frame",nil,button,"BackdropTemplate")
    bg:SetAllPoints()
    bg:SetFrameLevel(math.max(0,button:GetFrameLevel()-1))
    SetBackdrop(bg, danger and {0.20,0.055,0.055,0.96} or C.panel2, C.black)
    button.__BPMMFlatBG = bg

    local fs = button.GetFontString and button:GetFontString()
    if fs then
        fs:SetTextColor(C.text[1],C.text[2],C.text[3],1)
    end

    button:HookScript("OnEnter", function(self)
        if self.__BPMMFlatBG then
            self.__BPMMFlatBG:SetBackdropColor(C.hover[1],C.hover[2],C.hover[3],1)
            self.__BPMMFlatBG:SetBackdropBorderColor(C.accent[1],C.accent[2],C.accent[3],1)
        end
    end)
    button:HookScript("OnLeave", function(self)
        if self.__BPMMFlatBG then
            local b = danger and {0.20,0.055,0.055,0.96} or C.panel2
            self.__BPMMFlatBG:SetBackdropColor(b[1],b[2],b[3],b[4])
            self.__BPMMFlatBG:SetBackdropBorderColor(0,0,0,1)
        end
    end)
end

local function FlatEditBox(edit)
    if not edit or styled[edit] then return end
    styled[edit]=true
    if edit.Left then edit.Left:Hide() end
    if edit.Middle then edit.Middle:Hide() end
    if edit.Right then edit.Right:Hide() end

    local bg = CreateFrame("Frame",nil,edit,"BackdropTemplate")
    bg:SetPoint("TOPLEFT",-2,2)
    bg:SetPoint("BOTTOMRIGHT",2,-2)
    bg:SetFrameLevel(math.max(0,edit:GetFrameLevel()-1))
    SetBackdrop(bg,C.panel2,C.black)
    edit.__BPMMEditBG = bg
end

local function FlatScrollBar(sb)
    if not sb or styled[sb] then return end
    styled[sb]=true

    if sb.Background then sb.Background:Hide() end
    if sb.Track then sb.Track:Hide() end

    local thumb = sb.GetThumbTexture and sb:GetThumbTexture()
    if thumb then
        thumb:SetTexture("Interface\\Buttons\\WHITE8x8")
        thumb:SetVertexColor(0.25,0.25,0.28,1)
    end

    local up = sb.ScrollUpButton or sb.Back
    local down = sb.ScrollDownButton or sb.Forward
    if up then FlatButton(up) end
    if down then FlatButton(down) end
end

local function FlatTab(tab, selected)
    if not tab then return end
    if not tab.__BPMMTabBG then
        if tab.Left then tab.Left:Hide() end
        if tab.Middle then tab.Middle:Hide() end
        if tab.Right then tab.Right:Hide() end
        if tab.LeftActive then tab.LeftActive:Hide() end
        if tab.MiddleActive then tab.MiddleActive:Hide() end
        if tab.RightActive then tab.RightActive:Hide() end
        if tab.GetNormalTexture then HideTexture(tab:GetNormalTexture()) end
        if tab.GetPushedTexture then HideTexture(tab:GetPushedTexture()) end
        if tab.GetHighlightTexture then HideTexture(tab:GetHighlightTexture()) end
        if tab.GetCheckedTexture then HideTexture(tab:GetCheckedTexture()) end

        local bg = CreateFrame("Frame",nil,tab,"BackdropTemplate")
        bg:SetAllPoints()
        bg:SetFrameLevel(math.max(0,tab:GetFrameLevel()-1))
        SetBackdrop(bg,C.panel2,C.black)
        tab.__BPMMTabBG = bg
    end
    if selected then
        tab.__BPMMTabBG:SetBackdropColor(0.11,0.11,0.13,1)
        tab.__BPMMTabBG:SetBackdropBorderColor(C.accent[1],C.accent[2],C.accent[3],1)
    else
        tab.__BPMMTabBG:SetBackdropColor(C.panel2[1],C.panel2[2],C.panel2[3],1)
        tab.__BPMMTabBG:SetBackdropBorderColor(0,0,0,1)
    end
end

local function SkinBindPadSlots()
    for i=1,250 do
        local b=_G["BindPadSlot"..i]
        if b then
            if b.GetNormalTexture then HideTexture(b:GetNormalTexture()) end
            if b.GetPushedTexture then HideTexture(b:GetPushedTexture()) end
            if b.border then b.border:Hide() end
            if b.icon then RoundTexture(b.icon) end
        end
    end
end

local function SkinMegaIcons()
    for i=1,400 do
        for _,prefix in ipairs({"MegaMacro_Button","MegaMacro_PopupButton"}) do
            local b=_G[prefix..i]
            if b then
                local tex=b.Icon or b.icon or _G[prefix..i.."Icon"]
                if not tex and b.GetNormalTexture then tex=b:GetNormalTexture() end
                if tex then RoundTexture(tex) end
            end
        end
    end
    if MegaMacro_FrameSelectedMacroButtonIcon then
        RoundTexture(MegaMacro_FrameSelectedMacroButtonIcon)
    end
end

local function StripDecorativeRegions(frame)
    if not frame then return end
    for _,r in ipairs({frame:GetRegions()}) do
        if r and r.GetObjectType and r:GetObjectType()=="Texture" then
            local n=r.GetName and r:GetName() or ""
            local atlas=r.GetAtlas and r:GetAtlas()
            if n:find("Portrait") or n:find("Border") or n:find("Background") or n:find("Bg") then
                r:SetAlpha(0)
            elseif atlas and (tostring(atlas):find("ButtonFrame") or tostring(atlas):find("UI%-")) then
                r:SetAlpha(0)
            end
        end
    end
end

local function MakeTopDragArea(frame,key)
    if not frame or dragAreas[key] then return end
    frame:SetMovable(true)
    frame:SetClampedToScreen(true)

    local bar=CreateFrame("Frame",nil,frame)
    dragAreas[key]=bar
    bar:SetPoint("TOPLEFT",2,-2)
    bar:SetPoint("TOPRIGHT",-30,-2)
    bar:SetHeight(26)
    bar:EnableMouse(true)
    bar:RegisterForDrag("LeftButton")
    bar:SetFrameLevel(frame:GetFrameLevel()+30)

    local tex=bar:CreateTexture(nil,"BACKGROUND")
    tex:SetAllPoints()
    tex:SetColorTexture(0.07,0.07,0.08,0.95)

    bar:SetScript("OnDragStart",function()
        if InCombatLockdown() then return end
        if frame.SetMovable then frame:SetMovable(true) end
        if frame.IsMovable and not frame:IsMovable() then return end
        frame:StartMoving()
    end)
    bar:SetScript("OnDragStop",function()
        frame:StopMovingOrSizing()
        if key=="BindPad" and BindPadVars then
            local p,_,rp,x,y=frame:GetPoint(1)
            BindPadVars.BPMMWindowPosition={point=p,relativePoint=rp,x=x,y=y}
        elseif key=="MegaMacro" and MegaMacro_Window_OnDragStop then
            pcall(MegaMacro_Window_OnDragStop)
        end
    end)
end

local function RestoreBindPadPosition()
    if not BindPadFrame or not BindPadVars or not BindPadVars.BPMMWindowPosition then return end
    local p=BindPadVars.BPMMWindowPosition
    BindPadFrame:ClearAllPoints()
    BindPadFrame:SetPoint(p.point or "CENTER",UIParent,p.relativePoint or p.point or "CENTER",p.x or 0,p.y or 0)
end

local function SkinBindPad()
    if not BindPadFrame then return end
    CreateShell(BindPadFrame,C.bg)
    StripDecorativeRegions(BindPadFrame)
    MakeTopDragArea(BindPadFrame,"BindPad")

    if MacroFramePortrait and MacroFramePortrait:GetParent()==BindPadFrame then MacroFramePortrait:Hide() end

    for i=1,8 do
        local tab=_G["BindPadFrameTab"..i] or _G["BindPadTab"..i]
        if tab then
            FlatTab(tab, PanelTemplates_GetSelectedTab and PanelTemplates_GetSelectedTab(BindPadFrame)==i)
        end
    end

    for _,name in ipairs({
        "BindPadCloseButton",
        "BindPadFrameCloseButton",
        "BindPadShowLessSlotButton",
        "BindPadShowMoreSlotButton",
    }) do
        local b=_G[name]
        if b then FlatButton(b) end
    end

    if BindPadScrollFrame and BindPadScrollFrame.ScrollBar then
        FlatScrollBar(BindPadScrollFrame.ScrollBar)
    end

    SkinBindPadSlots()
end

local function SkinMegaMacro()
    if not MegaMacro_Frame then return end
    CreateShell(MegaMacro_Frame,C.bg)
    StripDecorativeRegions(MegaMacro_Frame)
    MakeTopDragArea(MegaMacro_Frame,"MegaMacro")

    if MegaMacro_FramePortrait then MegaMacro_FramePortrait:Hide() end
    if MegaMacro_HorizontalBarLeft then MegaMacro_HorizontalBarLeft:SetAlpha(0) end
    if MegaMacro_FrameSelectedMacroBackground then MegaMacro_FrameSelectedMacroBackground:SetAlpha(0) end

    for i=1,10 do
        local tab=_G["MegaMacro_FrameTab"..i]
        if tab then
            FlatTab(tab, PanelTemplates_GetSelectedTab and PanelTemplates_GetSelectedTab(MegaMacro_Frame)==i)
        end
    end

    for _,name in ipairs({
        "MegaMacro_FrameSaveButton",
        "MegaMacro_FrameDeleteButton",
        "MegaMacro_FrameExitButton",
        "MegaMacro_CloseButton",
        "MegaMacro_PopupCancelButton",
        "MegaMacro_PopupOkayButton",
    }) do
        local b=_G[name]
        if b then
            FlatButton(b, name:find("Delete") or name:find("Exit"))
        end
    end

    if MegaMacro_ButtonScrollFrame and MegaMacro_ButtonScrollFrame.ScrollBar then
        FlatScrollBar(MegaMacro_ButtonScrollFrame.ScrollBar)
    end
    if MegaMacro_IconScrollFrame and MegaMacro_IconScrollFrame.ScrollBar then
        FlatScrollBar(MegaMacro_IconScrollFrame.ScrollBar)
    end

    for _,name in ipairs({
        "MegaMacro_IconSearchBox",
        "MegaMacro_FrameText",
        "MegaMacro_FrameSelectedMacroNameEditBox",
        "MegaMacro_FallbackTextureEditBox",
    }) do
        local e=_G[name]
        if e then FlatEditBox(e) end
    end

    SkinMegaIcons()
end

function BPMM:RefreshStyle()
    SkinBindPad()
    SkinMegaMacro()
    SkinBindPadSlots()
    SkinMegaIcons()
end

function BPMM:InitializeStyle()
    -- Restore BindPad position once during initialization. Do not re-apply it
    -- during periodic style refreshes; doing so causes a visible hitch while dragging.
    RestoreBindPadPosition()
    SkinBindPad()
    SkinMegaMacro()

    if BindPadFrame then
        BindPadFrame:HookScript("OnShow",function()
            C_Timer.After(0,function() BPMM:RefreshStyle() end)
        end)
    end

    if MegaMacro_Frame then
        MegaMacro_Frame:HookScript("OnShow",function()
            C_Timer.After(0,function() BPMM:RefreshStyle() end)
            C_Timer.After(0.1,function() BPMM:RefreshStyle() end)
        end)
    end

    if not updateFrame then
        updateFrame=CreateFrame("Frame")
        local elapsed=0
        updateFrame:SetScript("OnUpdate",function(_,dt)
            elapsed=elapsed+dt
            if elapsed>=0.5 then
                elapsed=0
                if (BindPadFrame and BindPadFrame:IsShown()) or (MegaMacro_Frame and MegaMacro_Frame:IsShown()) then
                    BPMM:RefreshStyle()
                end
            end
        end)

        local function RefreshUpdateFrameVisibility()
            local shown=(BindPadFrame and BindPadFrame:IsShown())
                or (MegaMacro_Frame and MegaMacro_Frame:IsShown())
            elapsed=0
            if shown then updateFrame:Show() else updateFrame:Hide() end
        end

        if BindPadFrame then
            BindPadFrame:HookScript("OnShow",RefreshUpdateFrameVisibility)
            BindPadFrame:HookScript("OnHide",RefreshUpdateFrameVisibility)
        end
        if MegaMacro_Frame then
            MegaMacro_Frame:HookScript("OnShow",RefreshUpdateFrameVisibility)
            MegaMacro_Frame:HookScript("OnHide",RefreshUpdateFrameVisibility)
        end
        RefreshUpdateFrameVisibility()
    end
end
end
-- END: Style.lua

-- ============================================================
-- BEGIN: Stage4.lua
-- ============================================================
do
local _, addon = ...

local BPMM = _G.BPMM
if not BPMM then return end

-- Stage 4 visual polish. This deliberately does not touch SavedVariables,
-- macro execution, BindPad bindings, or MegaMacro's data engine.

local C = {
    bg      = {0.035,0.035,0.040,0.98},
    panel   = {0.060,0.060,0.070,0.98},
    panel2  = {0.085,0.085,0.095,1},
    accent  = {0.10,0.55,0.85,1},
    text    = {0.90,0.90,0.92,1},
    muted   = {0.55,0.55,0.58,1},
    black   = {0,0,0,1},
}

local done=setmetatable({}, {__mode="k"})

local function Backdrop(frame,bg,border)
    if not frame or not frame.SetBackdrop then return end
    frame:SetBackdrop({
        bgFile="Interface\\Buttons\\WHITE8x8",
        edgeFile="Interface\\Buttons\\WHITE8x8",
        edgeSize=1,
        insets={left=1,right=1,top=1,bottom=1},
    })
    bg=bg or C.panel
    border=border or C.black
    frame:SetBackdropColor(bg[1],bg[2],bg[3],bg[4])
    frame:SetBackdropBorderColor(border[1],border[2],border[3],border[4])
end

local function HideNamedPieces(prefix,suffixes)
    for _,suffix in ipairs(suffixes) do
        local r=_G[prefix..suffix]
        if r and r.Hide then r:Hide() elseif r and r.SetAlpha then r:SetAlpha(0) end
    end
end

local function SkinCloseButton(b)
    if not b or done[b] then return end
    done[b]=true
    if b.GetNormalTexture and b:GetNormalTexture() then b:GetNormalTexture():SetAlpha(0) end
    if b.GetPushedTexture and b:GetPushedTexture() then b:GetPushedTexture():SetAlpha(0) end
    if b.GetHighlightTexture and b:GetHighlightTexture() then b:GetHighlightTexture():SetAlpha(0) end
    b:SetSize(20,20)

    local bg=CreateFrame("Frame",nil,b,"BackdropTemplate")
    bg:SetAllPoints()
    bg:SetFrameLevel(math.max(0,b:GetFrameLevel()-1))
    Backdrop(bg,C.panel2,C.black)

    local x=b:CreateFontString(nil,"OVERLAY","GameFontNormal")
    x:SetPoint("CENTER",0,0)
    x:SetText("X")
    x:SetTextColor(.9,.9,.9,1)
    b.__BPMMCloseBG=bg
    b.__BPMMCloseX=x

    b:HookScript("OnEnter",function()
        bg:SetBackdropColor(.18,.055,.055,1)
        bg:SetBackdropBorderColor(.65,.15,.15,1)
    end)
    b:HookScript("OnLeave",function()
        bg:SetBackdropColor(C.panel2[1],C.panel2[2],C.panel2[3],1)
        bg:SetBackdropBorderColor(0,0,0,1)
    end)
end

local function SkinScrollBar(sb)
    if not sb or sb.__BPMMStage4 then return end
    sb.__BPMMStage4=true

    if sb.Background then sb.Background:SetAlpha(0) end
    if sb.Track then sb.Track:SetAlpha(0) end

    local thumb=sb.GetThumbTexture and sb:GetThumbTexture()
    if thumb then
        thumb:SetTexture("Interface\\Buttons\\WHITE8x8")
        thumb:SetVertexColor(.28,.28,.31,1)
        thumb:SetWidth(8)
    end

    for _,b in ipairs({sb.ScrollUpButton,sb.ScrollDownButton,sb.Back,sb.Forward}) do
        if b then
            if b.GetNormalTexture and b:GetNormalTexture() then b:GetNormalTexture():SetAlpha(0) end
            if b.GetPushedTexture and b:GetPushedTexture() then b:GetPushedTexture():SetAlpha(0) end
            if b.GetHighlightTexture and b:GetHighlightTexture() then b:GetHighlightTexture():SetAlpha(0) end
            b:SetAlpha(.85)
        end
    end
end

local function SkinInset(frame)
    if not frame or frame.__BPMMStage4Inset then return end
    frame.__BPMMStage4Inset=true

    for _,r in ipairs({frame:GetRegions()}) do
        if r and r.GetObjectType and r:GetObjectType()=="Texture" then
            r:SetAlpha(0)
        end
    end

    if frame.SetBackdrop then
        Backdrop(frame,C.panel,C.black)
    else
        local bg=CreateFrame("Frame",nil,frame,"BackdropTemplate")
        bg:SetAllPoints()
        bg:SetFrameLevel(math.max(0,frame:GetFrameLevel()-1))
        Backdrop(bg,C.panel,C.black)
        frame.__BPMMInsetBG=bg
    end
end

local function SkinTab(tab,selected)
    if not tab then return end

    local name=tab.GetName and tab:GetName()
    if name then
        HideNamedPieces(name,{"Left","Middle","Right","LeftActive","MiddleActive","RightActive"})
    end
    if tab.Left then tab.Left:SetAlpha(0) end
    if tab.Middle then tab.Middle:SetAlpha(0) end
    if tab.Right then tab.Right:SetAlpha(0) end

    if not tab.__BPMMStage4BG then
        local bg=CreateFrame("Frame",nil,tab,"BackdropTemplate")
        bg:SetPoint("TOPLEFT",1,-1)
        bg:SetPoint("BOTTOMRIGHT",-1,1)
        bg:SetFrameLevel(math.max(0,tab:GetFrameLevel()-1))
        Backdrop(bg,C.panel2,C.black)
        tab.__BPMMStage4BG=bg
    end

    local bg=tab.__BPMMStage4BG
    if selected then
        bg:SetBackdropColor(.11,.11,.13,1)
        bg:SetBackdropBorderColor(C.accent[1],C.accent[2],C.accent[3],1)
    else
        bg:SetBackdropColor(C.panel2[1],C.panel2[2],C.panel2[3],1)
        bg:SetBackdropBorderColor(0,0,0,1)
    end

    local fs=tab.GetFontString and tab:GetFontString()
    if fs then
        if selected then fs:SetTextColor(1,1,1,1)
        else fs:SetTextColor(.72,.72,.75,1) end
    end
end

local function SkinButton(b,danger)
    if not b or b.__BPMMStage4Button then return end
    b.__BPMMStage4Button=true

    if b.GetNormalTexture and b:GetNormalTexture() then b:GetNormalTexture():SetAlpha(0) end
    if b.GetPushedTexture and b:GetPushedTexture() then b:GetPushedTexture():SetAlpha(0) end
    if b.GetHighlightTexture and b:GetHighlightTexture() then b:GetHighlightTexture():SetAlpha(0) end
    if b.GetDisabledTexture and b:GetDisabledTexture() then b:GetDisabledTexture():SetAlpha(0) end

    local bg=CreateFrame("Frame",nil,b,"BackdropTemplate")
    bg:SetAllPoints()
    bg:SetFrameLevel(math.max(0,b:GetFrameLevel()-1))
    local base=danger and {0.19,.05,.05,1} or C.panel2
    Backdrop(bg,base,C.black)
    b.__BPMMStage4ButtonBG=bg

    local fs=b.GetFontString and b:GetFontString()
    if fs then fs:SetTextColor(.9,.9,.92,1) end

    b:HookScript("OnEnter",function()
        bg:SetBackdropColor(.15,.15,.17,1)
        bg:SetBackdropBorderColor(C.accent[1],C.accent[2],C.accent[3],1)
    end)
    b:HookScript("OnLeave",function()
        bg:SetBackdropColor(base[1],base[2],base[3],base[4])
        bg:SetBackdropBorderColor(0,0,0,1)
    end)
end

local function PolishMegaMacro()
    if not MegaMacro_Frame then return end

    -- Remove remaining portrait/title-border art.
    for _,name in ipairs({
        "MegaMacro_FramePortrait",
        "MegaMacro_FramePortraitFrame",
        "MegaMacro_HorizontalBarLeft",
        "MegaMacro_HorizontalBarRight",
        "MegaMacro_FrameBg",
        "MegaMacro_FrameBackground",
    }) do
        local o=_G[name]
        if o and o.SetAlpha then o:SetAlpha(0) end
    end

    for _,name in ipairs({
        "MegaMacro_FrameInset",
        "MegaMacro_FrameMacroFrame",
        "MegaMacro_FrameSelectedMacro",
        "MegaMacro_PopupFrame",
    }) do
        SkinInset(_G[name])
    end

    local selected=PanelTemplates_GetSelectedTab and PanelTemplates_GetSelectedTab(MegaMacro_Frame)
    for i=1,10 do
        SkinTab(_G["MegaMacro_FrameTab"..i], selected==i)
    end

    for _,name in ipairs({
        "MegaMacro_FrameSaveButton",
        "MegaMacro_PopupOkayButton",
        "MegaMacro_PopupCancelButton",
    }) do SkinButton(_G[name],false) end

    for _,name in ipairs({
        "MegaMacro_FrameDeleteButton",
        "MegaMacro_FrameExitButton",
    }) do SkinButton(_G[name],true) end

    for _,name in ipairs({
        "MegaMacro_CloseButton",
        "MegaMacro_FrameCloseButton",
        "MegaMacro_PopupFrameCloseButton",
    }) do SkinCloseButton(_G[name]) end

    for _,sf in ipairs({
        MegaMacro_ButtonScrollFrame,
        MegaMacro_IconScrollFrame,
        MegaMacro_PopupScrollFrame,
    }) do
        if sf and sf.ScrollBar then SkinScrollBar(sf.ScrollBar) end
    end
end

local function PolishBindPad()
    if not BindPadFrame then return end

    -- Suppress the remaining Blizzard macro-frame style ornaments.
    for _,r in ipairs({BindPadFrame:GetRegions()}) do
        if r and r.GetObjectType and r:GetObjectType()=="Texture" then
            local atlas=r.GetAtlas and r:GetAtlas()
            local name=r.GetName and r:GetName() or ""
            if name:find("Portrait") or name:find("Border") or
               (atlas and tostring(atlas):find("UI%-")) then
                r:SetAlpha(0)
            end
        end
    end

    local selected=PanelTemplates_GetSelectedTab and PanelTemplates_GetSelectedTab(BindPadFrame)
    for i=1,10 do
        SkinTab(_G["BindPadFrameTab"..i] or _G["BindPadTab"..i],selected==i)
    end

    for _,name in ipairs({
        "BindPadCloseButton",
        "BindPadFrameCloseButton",
    }) do SkinCloseButton(_G[name]) end

    for _,name in ipairs({
        "BindPadShowLessSlotButton",
        "BindPadShowMoreSlotButton",
    }) do SkinButton(_G[name],false) end

    for _,sf in ipairs({
        BindPadScrollFrame,
        BindPadFrameScrollFrame,
    }) do
        if sf and sf.ScrollBar then SkinScrollBar(sf.ScrollBar) end
    end
end

function BPMM:Stage4Polish()
    PolishBindPad()
    PolishMegaMacro()
end

local f=CreateFrame("Frame")
f:RegisterEvent("PLAYER_LOGIN")
f:SetScript("OnEvent",function()
    C_Timer.After(.25,function() BPMM:Stage4Polish() end)
end)

if BindPadFrame then
    BindPadFrame:HookScript("OnShow",function()
        C_Timer.After(0,function() BPMM:Stage4Polish() end)
    end)
end

if MegaMacro_Frame then
    MegaMacro_Frame:HookScript("OnShow",function()
        C_Timer.After(0,function() BPMM:Stage4Polish() end)
        C_Timer.After(.1,function() BPMM:Stage4Polish() end)
    end)
end
end
-- END: Stage4.lua

-- ============================================================
-- BEGIN: Stage4_1.lua
-- ============================================================
do
local _, addon = ...

local BPMM = _G.BPMM
if not BPMM then return end

-- Stage 4.1
-- UI-only changes. No SavedVariables migration and no macro/binding engine changes.

local hooked = setmetatable({}, {__mode="k"})

local function HideFrame(frame)
    if not frame then return end
    frame:Hide()
    frame:SetAlpha(0)
    if frame.EnableMouse then frame:EnableMouse(false) end
end

local function HideByNames(names)
    for _,name in ipairs(names) do
        HideFrame(_G[name])
    end
end

local function RemoveBottomButtons()
    -- Bottom Exit buttons: close is handled exclusively by the Stage 4 top-right X.
    HideByNames({
        "BindPadExitButton",
        "BindPadFrameExitButton",
        "MegaMacro_FrameExitButton",
        "MegaMacro_ExitButton",
    })

    -- MegaMacro Lock and redundant legacy Edit controls.  The primary
    -- MegaMacro_EditButton is part of the current editor and must remain
    -- visible and clickable.
    HideByNames({
        "MegaMacro_LockButton",
        "MegaMacro_FrameLockButton",
        "MegaMacro_FrameEditButton",
        "MegaMacro_FrameSelectedMacroEditButton",
    })
end

local function GetBindPadScrollFrame()
    return _G.BindPadScrollFrame or _G.BindPadFrameScrollFrame
end

local function GetScrollBar(sf)
    if not sf then return end
    return sf.ScrollBar or _G[(sf:GetName() or "").."ScrollBar"]
end

local function ScrollBindPad(delta)
    local sf = GetBindPadScrollFrame()
    if not sf then return end

    local range = sf.GetVerticalScrollRange and sf:GetVerticalScrollRange() or 0
    if not range or range <= 0 then return end

    local current = sf.GetVerticalScroll and sf:GetVerticalScroll() or 0
    local amount = 72
    local target = current - (delta * amount)
    target = math.max(0, math.min(range, target))

    if sf.SetVerticalScroll then
        sf:SetVerticalScroll(target)
    end
end
local function EnableBindPadMouseWheel()
    local targets = {
        _G.BindPadFrame,
        GetBindPadScrollFrame(),
    }

    for _,frame in ipairs(targets) do
        if frame and not frame.__BPMMWheel41 then
            frame.__BPMMWheel41 = true
            frame:EnableMouseWheel(true)
            frame:HookScript("OnMouseWheel", function(_,delta)
                if IsShiftKeyDown and IsShiftKeyDown() then return end
                ScrollBindPad(delta)
            end)
        end
    end

    local sf = GetBindPadScrollFrame()
    local sb = GetScrollBar(sf)
    if sb then
        -- No arrow buttons; the thumb remains available when there is overflow.
        HideFrame(sb.ScrollUpButton or sb.Back)
        HideFrame(sb.ScrollDownButton or sb.Forward)

        -- Modern Retail MinimalScrollBar is a scroll controller and no longer
        -- exposes the legacy GetMinMaxValues API. Leave visibility/state to
        -- Blizzard's controller and only suppress the arrow buttons.
    end
end

local function FindProfileButtons()
    local found = {}

    -- Known/common naming patterns first.
    for i=1,4 do
        local candidates = {
            _G["BindPadProfileButton"..i],
            _G["BindPadFrameProfileButton"..i],
            _G["BindPadProfile"..i],
            _G["BindPadFrameProfile"..i],
        }
        for _,b in ipairs(candidates) do
            if b then
                found[#found+1] = b
                break
            end
        end
    end

    -- Fallback: inspect BindPad children for Profile 1..4 labels/names.
    if #found < 4 and BindPadFrame then
        for _,child in ipairs({BindPadFrame:GetChildren()}) do
            if child and not child.__BPMMProfileFound then
                local n = child.GetName and child:GetName() or ""
                local text
                if child.GetText then text = child:GetText() end
                if (n and n:lower():find("profile")) or
                   (text and tostring(text):lower():find("profile")) then
                    child.__BPMMProfileFound = true
                    found[#found+1] = child
                end
            end
        end
    end

    return found
end

local function GetButtonIconRegion(button)
    if not button then return end
    if button.icon then return button.icon end
    if button.Icon then return button.Icon end
    local n = button.GetName and button:GetName()
    if n then
        return _G[n.."Icon"] or _G[n.."IconTexture"]
    end
    if button.GetNormalTexture then
        return button:GetNormalTexture()
    end
end

local function GetClassSpecs()
    local specs = {}
    local count = GetNumSpecializations and GetNumSpecializations() or 0
    for i=1,count do
        local specID, name, description, icon, role = GetSpecializationInfo(i)
        if specID then
            specs[#specs+1] = {
                index=i,
                id=specID,
                name=name,
                icon=icon,
                role=role,
            }
        end
    end
    return specs
end

local function UpdateProfileIcons()
    for i=1,5 do
        local button=_G["BindPadProfileTab"..i]
        if button and BindPadProfileTab_OnShow then
            BindPadProfileTab_OnShow(button)
        end
    end
end
local function HideBindingsRow()
    -- Stage 4.1 mockup removed the redundant "Bindings" label/row.
    HideByNames({
        "BindPadBindingsLabel",
        "BindPadFrameBindingsLabel",
        "BindPadBindingsText",
        "BindPadFrameBindingsText",
    })

    if BindPadFrame then
        for _,region in ipairs({BindPadFrame:GetRegions()}) do
            if region and region.GetObjectType and region:GetObjectType()=="FontString" then
                local text = region:GetText()
                if text and text:lower():gsub("%s+","") == "bindings" then
                    region:Hide()
                end
            end
        end
    end
end

local function PositionProfilesAtBottom()
    if not BindPadFrame then return end

    if BindPadScrollFrame then
        BindPadScrollFrame:SetHeight(330)
    end

    local startX=108
    local y=82
    local spacing=42

    for i=1,5 do
        local b=_G["BindPadProfileTab"..i]
        if b then
            b:ClearAllPoints()
            b:SetPoint("BOTTOMLEFT",BindPadFrame,"BOTTOMLEFT",startX+(i-1)*spacing,y)
            b:SetSize(32,32)

            local bg=_G["BindPadProfileTab"..i.."Background"]
            if bg then bg:SetAlpha(0) end

            if BindPadProfileTab_OnShow then
                BindPadProfileTab_OnShow(b)
            end
        end
    end
end
local function Refresh()
    RemoveBottomButtons()
    HideBindingsRow()
    EnableBindPadMouseWheel()
    PositionProfilesAtBottom()
    UpdateProfileIcons()
end

function BPMM:Stage41Refresh()
    Refresh()
end

local eventFrame=CreateFrame("Frame")
eventFrame:RegisterEvent("PLAYER_LOGIN")
eventFrame:RegisterEvent("PLAYER_SPECIALIZATION_CHANGED")
eventFrame:RegisterEvent("ACTIVE_TALENT_GROUP_CHANGED")
eventFrame:SetScript("OnEvent",function(_,event,unit)
    if event=="PLAYER_SPECIALIZATION_CHANGED" and unit and unit~="player" then return end
    C_Timer.After(.1,Refresh)
end)

if BindPadFrame then
    BindPadFrame:HookScript("OnShow",function()
        C_Timer.After(0,Refresh)
        C_Timer.After(.1,Refresh)
    end)
end

if MegaMacro_Frame then
    MegaMacro_Frame:HookScript("OnShow",function()
        C_Timer.After(0,Refresh)
    end)
end
end
-- END: Stage4_1.lua

-- ============================================================
-- BEGIN: RemoveMegaMacroLock.lua
-- ============================================================
do
local f = CreateFrame("Frame")

local function RemoveMegaMacroLock()
    local names = {
        "MegaMacro_LockButton",
        "MegaMacro_FrameLockButton",
        "MegaMacroLockButton",
        "MegaMacro_WindowLockButton",
        "MegaMacro_FrameLock",
    }

    for _, name in ipairs(names) do
        local b = _G[name]
        if b then
            b:Hide()
            b:SetAlpha(0)
            if b.EnableMouse then b:EnableMouse(false) end
            if b.UnregisterAllEvents then b:UnregisterAllEvents() end
        end
    end

    -- Fallback for this MegaMacro build: locate the top-right button whose
    -- visible text is "Lock", without affecting the close X.
    if MegaMacro_Frame then
        for _, child in ipairs({MegaMacro_Frame:GetChildren()}) do
            if child and child.GetText then
                local ok, text = pcall(child.GetText, child)
                if ok and text and tostring(text):lower() == "lock" then
                    child:Hide()
                    child:SetAlpha(0)
                    if child.EnableMouse then child:EnableMouse(false) end
                end
            end
        end
    end
end

f:RegisterEvent("PLAYER_LOGIN")
f:SetScript("OnEvent", function()
    C_Timer.After(0, RemoveMegaMacroLock)
    C_Timer.After(0.5, RemoveMegaMacroLock)
end)

if MegaMacro_Frame then
    MegaMacro_Frame:HookScript("OnShow", function()
        C_Timer.After(0, RemoveMegaMacroLock)
    end)
end
end
-- END: RemoveMegaMacroLock.lua
